// This file is auto-generated by @hey-api/openapi-ts
import type { CancelablePromise } from "./core/CancelablePromise";
import { OpenAPI } from "./core/OpenAPI";
import { request as __request } from "./core/request";
import type { CreateTokenData, CreateTokenResponse } from "./types.gen";

export class KeycloakAuthManagerLoginService {
  /**
   * Create Token
   * Generate a new API token.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns LoginResponse Successful Response
   * @throws ApiError
   */
  public static createToken(data: CreateTokenData): CancelablePromise<CreateTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/token",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        400: "Bad Request",
        401: "Unauthorized",
        422: "Validation Error",
      },
    });
  }
}
