// This file is auto-generated by @hey-api/openapi-ts

export const $HTTPExceptionResponse = {
  properties: {
    detail: {
      anyOf: [
        {
          type: "string",
        },
        {
          additionalProperties: true,
          type: "object",
        },
      ],
      title: "Detail",
    },
  },
  type: "object",
  required: ["detail"],
  title: "HTTPExceptionResponse",
  description: "HTTPException Model used for error response.",
} as const;

export const $HTTPValidationError = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const $LoginBody = {
  properties: {
    username: {
      type: "string",
      title: "Username",
    },
    password: {
      type: "string",
      title: "Password",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["username", "password"],
  title: "LoginBody",
  description: "Login serializer for post bodies.",
} as const;

export const $LoginResponse = {
  properties: {
    access_token: {
      type: "string",
      title: "Access Token",
    },
  },
  type: "object",
  required: ["access_token"],
  title: "LoginResponse",
  description: "Login serializer for responses.",
} as const;

export const $UserRequest = {
  properties: {
    username: {
      type: "string",
      title: "Username",
    },
    email: {
      type: "string",
      format: "email",
      title: "Email",
    },
    first_name: {
      type: "string",
      title: "First Name",
    },
    last_name: {
      type: "string",
      title: "Last Name",
    },
    enabled: {
      type: "boolean",
      title: "Enabled",
      default: true,
    },
    email_verified: {
      type: "boolean",
      title: "Email Verified",
      default: false,
    },
    role: {
      type: "string",
      title: "Role",
    },
    password: {
      type: "string",
      title: "Password",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["username", "email", "first_name", "last_name", "role", "password"],
  title: "UserRequest",
} as const;

export const $UserResponse = {
  properties: {
    userid: {
      type: "string",
      title: "Userid",
    },
    username: {
      type: "string",
      title: "Username",
    },
    email: {
      type: "string",
      format: "email",
      title: "Email",
    },
    first_name: {
      type: "string",
      title: "First Name",
    },
    last_name: {
      type: "string",
      title: "Last Name",
    },
    enabled: {
      type: "boolean",
      title: "Enabled",
    },
    email_verified: {
      type: "boolean",
      title: "Email Verified",
    },
    roles: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Roles",
    },
    created_timestamp: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Created Timestamp",
    },
  },
  type: "object",
  required: ["userid", "username", "email", "first_name", "last_name", "enabled", "email_verified", "roles"],
  title: "UserResponse",
} as const;

export const $UserUpdateRequest = {
  properties: {
    username: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Username",
    },
    email: {
      anyOf: [
        {
          type: "string",
          format: "email",
        },
        {
          type: "null",
        },
      ],
      title: "Email",
    },
    firstName: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Firstname",
    },
    lastName: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Lastname",
    },
    enabled: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Enabled",
    },
    emailVerified: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Emailverified",
    },
    role: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Role",
    },
    password: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Password",
    },
  },
  additionalProperties: false,
  type: "object",
  title: "UserUpdateRequest",
} as const;

export const $ValidationError = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;
