// This file is auto-generated by @hey-api/openapi-ts
import type { CancelablePromise } from "./core/CancelablePromise";
import { OpenAPI } from "./core/OpenAPI";
import { request as __request } from "./core/request";
import type {
  CreateTokenData,
  CreateTokenResponse,
  GetUsersResponse,
  CreateUserData,
  CreateUserResponse,
  UpdateUserData,
  UpdateUserResponse,
  DeleteUserData,
  DeleteUserResponse,
} from "./types.gen";

export class KeycloakAuthManagerLoginService {
  /**
   * Create Token
   * Generate a new API token.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns LoginResponse Successful Response
   * @throws ApiError
   */
  public static createToken(data: CreateTokenData): CancelablePromise<CreateTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/auth/token",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        400: "Bad Request",
        401: "Unauthorized",
        422: "Validation Error",
      },
    });
  }
}

export class KeycloakAuthManagerSecurityService {
  /**
   * Get Users
   * @returns UserResponse Successful Response
   * @throws ApiError
   */
  public static getUsers(): CancelablePromise<GetUsersResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/auth/users",
      errors: {
        400: "Bad Request",
        401: "Unauthorized",
      },
    });
  }

  /**
   * Create User
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserResponse Successful Response
   * @throws ApiError
   */
  public static createUser(data: CreateUserData): CancelablePromise<CreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/auth/users",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        400: "Bad Request",
        401: "Unauthorized",
        409: "Conflict",
        422: "Validation Error",
      },
    });
  }

  /**
   * Update User
   * @param data The data for the request.
   * @param data.userid
   * @param data.requestBody
   * @returns void Successful Response
   * @throws ApiError
   */
  public static updateUser(data: UpdateUserData): CancelablePromise<UpdateUserResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/auth/users/{userid}",
      path: {
        userid: data.userid,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        400: "Bad Request",
        401: "Unauthorized",
        409: "Conflict",
        422: "Validation Error",
      },
    });
  }

  /**
   * Delete User
   * @param data The data for the request.
   * @param data.userid
   * @returns void Successful Response
   * @throws ApiError
   */
  public static deleteUser(data: DeleteUserData): CancelablePromise<DeleteUserResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/auth/users/{userid}",
      path: {
        userid: data.userid,
      },
      errors: {
        400: "Bad Request",
        401: "Unauthorized",
        422: "Validation Error",
      },
    });
  }
}
